### ISSUE TITLE
Images not aligning correctly

### ISSUE THREAD

**Issue by sachinsenal0x64** [Rolv-Apneseth/tfm.nvim#14]
![image](https://github.com/Rolv-Apneseth/tfm.nvim/assets/127573781/2b2e5c4d-9034-4adb-8b55-115597d1df6e)

**Comment by Rolv-Apneseth** [comment]
I don't believe that's related to this plugin. I was having that issue with `yazi` for a while, latest branch seems to work fine for me. What terminal emulator + terminal file manager combo is this?

**Comment by sachinsenal0x64** [comment]
It's Kitty 

Yazi without this plugin 

![image](https://github.com/Rolv-Apneseth/tfm.nvim/assets/127573781/57def811-ea47-499c-b5f5-c7a6790409f9)

**Comment by Rolv-Apneseth** [comment]
Yeah I think there's some issue with the kitty image protocol in Neovim, so it must be falling back to something else while using this plugin. Have a look at [this issue](https://github.com/Rolv-Apneseth/tfm.nvim/issues/9) and try this:

> What happens with the image previews if you just do :term and call yazi in there? I assume that would still be blurry.
