### ISSUE TITLE
E492: Not an editor command: Tfm

### ISSUE THREAD

**Issue by danbruegge** [Rolv-Apneseth/tfm.nvim#6]
Hi, thanks for your plugin. Currently, I'm trying it out to use it with yazi.

After installation, there is no `Tfm` command.
![2024-01-26_15 48 40](https://github.com/Rolv-Apneseth/tfm.nvim/assets/1296438/6738f8a5-1dbc-441f-9851-d9cb294d1d88)

```lua
return {
  "rolv-apneseth/tfm.nvim",
  lazy = false,
  opts = {
    replace_netrw = true,
  },
  keys = {
    { "<leader>e", ":Tfm<CR>", desc = "TFM" },
  },
}
```

Currently, I have no idea how to solve it. The good thing, basically it is working as a netrw replacement. If I open nvim with a folder, it opens up yazi right away.

With `"<leader>e", ':lua require("tfm").open()<CR>'` it is working.

Nvim version:
![2024-01-26_16 39 48](https://github.com/Rolv-Apneseth/tfm.nvim/assets/1296438/e2e8d074-a999-4a32-b542-1d2f274bbda1)

Using it on an Mac M2.

**Comment by Wansmer** [comment]
Hi! I think you need to set `enable_cmds` to `true` in opts. By [default](https://github.com/Rolv-Apneseth/tfm.nvim#full) it is `false`.

**Comment by danbruegge** [comment]
Ahh, nice. Thanks, this solved it. Strange that I missed this option. 

Why is this option not enabled by default?
