### ISSUE TITLE
Error when opening into directory with option `replace_netrw = true`

### ISSUE THREAD

**Issue by fmorroni** [Rolv-Apneseth/tfm.nvim#7]
Hi, I'm trying out the plugin on my lunarvim setup. Everything seems to be working except when opening directly into a directory like `lvim some-dir` which throws the error:
```
Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2(): Vim(normal):Can't re-enter normal mode from terminal mode
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...l/share/lunarvim/site/pack/lazy/opt/lir.nvim/lua/lir.lua:130: in function <...l/share/lunarvim/site/pack/lazy/opt/lir.nvim/lua/lir.lua:129>
```
Considering the traceback shows a lunarvim related file, I'm assuming the problem may be coming from their side, but I thought I'd ask here first just in case.

Btw after that error everything seems to keep working fine, it's just a mild annoyance.

**Comment by Rolv-Apneseth** [comment]
Very sorry, seems I wasn't getting notifications for this repo. I'll look into this issue and the other one you posted. My bad.

**Comment by Rolv-Apneseth** [comment]
> ```
> Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2(): Vim(normal):Can't re-enter normal mode from terminal mode
> stack traceback:
>         [C]: in function 'nvim_exec2'
>         vim/_editor.lua: in function 'cmd'
>         ...l/share/lunarvim/site/pack/lazy/opt/lir.nvim/lua/lir.lua:130: in function <...l/share/lunarvim/site/pack/lazy/opt/lir.nvim/lua/lir.lua:129>
> ```

Looks like it's re-trying to enter insert mode. I found these lines in `LunarVim`:

```
lua/lvim/core/terminal.lua
15:    start_in_insert = true,
```

I'm not sure how this "distro" works, but can you change that option in your config and see if the error still happens?

**Comment by Rolv-Apneseth** [comment]
> I am not sure if this is related, but on a vanilla [LazyVim](https://github.com/LazyVim/LazyVim) installation, `replace_netrw = true` does not seem to have any effect. Opening directories with `nvim` still opens them in `netrw`.

This might be a separate issue. Off the top of my head, are you maybe lazy loading the plugin?

**Comment by fmorroni** [comment]
> Looks like it's re-trying to enter insert mode. I found these lines in `LunarVim`:
> 
> ```
> lua/lvim/core/terminal.lua
> 15:    start_in_insert = true,
> ```
> 
> I'm not sure how this "distro" works, but can you change that option in your config and see if the error still happens?

Hi thanks for looking into it. Unfortunately that didn't solve the problem, the same error is still being thrown.
It really doesn't matter tho, and it's clearly a problem with my/lunarvim's config so don't worry about it haha

**Comment by Rolv-Apneseth** [comment]
Ah it's an annoying error though, I'll try help if I can.

The error message points to `lua/lvim/core/lir.lua`, where I believe that's a config file for [this plugin](https://github.com/tamago324/lir.nvim), a file explorer, which would probably conflict with this plugin. Try disabling that one (I guess set that `active = false`?) and see if the error persists.

**Comment by fmorroni** [comment]
> The error message points to `lua/lvim/core/lir.lua`, where I believe that's a config file for [this plugin](https://github.com/tamago324/lir.nvim), a file explorer, which would probably conflict with this plugin. Try disabling that one (I guess set that `active = false`?) and see if the error persists.

Yep, that was it. I had no idea that plugin existed... but it seems it's the one that was used for opening directories (I thought it was nvimtree). Disabling it with `lvim.builtin.lir.active = false` solved the error. Thanks!
